### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by enbyspiders** [enbyspiders/haxepunk.com#1]
- [ ] Redesigning the **website structure and style** to make it a bit more modern and user-friendly
- [ ] Updating the **HaxePunk logo**
- [ ] Improving on the **documentation**, updating outdated info, adding more tutorials, faqs etc.
- [ ] Adding more **demos** and also improving the games page
- [ ] Updating the **forum software**, maybe even migrating to a different setup -- I personally feel that [discourse](https://github.com/discourse/discourse) might be a good idea**
- [ ] Creating some icons and graphics for https://twitter.com/HaxePunk
